Repository NewFit/NewFit-Backend, pull requests merged in 2023-10, with the labels that each got.

#173 refactor: TokenAuthenticationFilter 내부 로직 수정 (#172)
  src/main/java/com/newfit/reservation/common/auth/jwt/TokenAuthenticationFilter.java
  src/main/java/com/newfit/reservation/common/auth/jwt/TokenProvider.java
  src/main/java/com/newfit/reservation/common/auth/oauth/handler/OAuth2SuccessHandler.java
  src/main/java/com/newfit/reservation/controller/AuthorityApiController.java
  src/main/java/com/newfit/reservation/controller/UserApiController.java
  src/main/java/com/newfit/reservation/service/AuthorityService.java
  src/main/java/com/newfit/reservation/service/UserService.java
Labels: refactor

#181 docs: chore 이슈 및 PR 템플릿 반영
  .github/ISSUE_TEMPLATE/🔧-chore.md
  .github/pull_request_template.md
Labels: docs

#182 feat: User modify 실행 시 nickname 변경하면 JWT 새로 발급하는 로직 구현 (#177)
  src/main/java/com/newfit/reservation/controller/UserApiController.java
  src/main/java/com/newfit/reservation/exception/ErrorCode.java
  src/main/java/com/newfit/reservation/service/UserService.java
Labels: feature

#185 feat: Reservation End 시점에 Credit을 생성하는 기능 추가 (#184)
  src/main/java/com/newfit/reservation/service/reservation/ReservationService.java
Labels: feature

#189 refactor: Builder 어노테이션 접근 제한자 적용
  src/main/java/com/newfit/reservation/controller/ReservationApiController.java
  src/main/java/com/newfit/reservation/domain/User.java
  src/main/java/com/newfit/reservation/domain/auth/OAuthHistory.java
  src/main/java/com/newfit/reservation/domain/auth/RefreshToken.java
  src/main/java/com/newfit/reservation/domain/dev/Proposal.java
  src/main/java/com/newfit/reservation/domain/dev/Report.java
  src/main/java/com/newfit/reservation/domain/equipment/Equipment.java
  src/main/java/com/newfit/reservation/domain/equipment/EquipmentGym.java
  src/main/java/com/newfit/reservation/domain/reservation/Reservation.java
  src/main/java/com/newfit/reservation/dto/response/GymResponse.java
  src/main/java/com/newfit/reservation/dto/response/RoutineReservationListResponse.java
  src/main/java/com/newfit/reservation/dto/response/UserDetailResponse.java
  src/main/java/com/newfit/reservation/service/reservation/ReservationService.java
Labels: refactor

#192 docs: readme 작성 (#174)
  README.md
Labels: docs

#193 refactor: ReservationService를 분리 (#187)
  src/main/java/com/newfit/reservation/domains/credit/service/CreditService.java
  src/main/java/com/newfit/reservation/domains/equipment/repository/EquipmentGymRepository.java
  src/main/java/com/newfit/reservation/domains/reservation/controller/ReservationApiController.java
  src/main/java/com/newfit/reservation/domains/reservation/service/ReservationService.java
  src/main/java/com/newfit/reservation/domains/routine/service/RoutineService.java
Labels: refactor

#194 refactor: 기구 사용 기능 가독성 개선 (#190)
  src/main/java/com/newfit/reservation/domains/reservation/service/ReservationService.java
Labels: refactor

#196 refactor: validateTagAt 메소드 내부에서 임시로 설정한 시간 정보 수정 (#195)
  src/main/java/com/newfit/reservation/domains/reservation/service/ReservationService.java
Labels: refactor

#203 remove: 불필요한 경로 제거 (#201)
  src/main/java/com/newfit/reservation/domains/authority/service/AuthorityService.java
Labels: chore

#204 refactor: for문을 제거하고 stream으로 대체 (#200)
  src/main/java/com/newfit/reservation/domains/authority/dto/response/manager/UserAndPendingListResponse.java
  src/main/java/com/newfit/reservation/domains/authority/service/AuthorityService.java
Labels: refactor

#207 refactor: query의 개선을 통해 service의 로직을 단순화합니다. (#202)
  src/main/java/com/newfit/reservation/domains/equipment/dto/response/EquipmentGymListResponse.java
  src/main/java/com/newfit/reservation/domains/equipment/repository/EquipmentGymRepository.java
  src/main/java/com/newfit/reservation/domains/equipment/service/EquipmentGymService.java
Labels: refactor

#210 refactor: RoutineService updateRoutine 메소드에서 이름 중복 체크 하도록 수정 (#209)
  src/main/java/com/newfit/reservation/domains/routine/service/RoutineService.java
Labels: refactor

#212 refactor: EquipmentService registerEquipment 메소드 내부 불필요한 if문 제거 (#211)
  src/main/java/com/newfit/reservation/common/exception/ErrorCode.java
  src/main/java/com/newfit/reservation/domains/equipment/service/EquipmentService.java
Labels: refactor

#208 refactor: patch 로직 일부를 서비스에서 도메인으로 이동 (#198)
  src/main/java/com/newfit/reservation/domains/reservation/domain/Reservation.java
  src/main/java/com/newfit/reservation/domains/reservation/service/ReservationService.java
  src/main/java/com/newfit/reservation/domains/user/domain/User.java
  src/main/java/com/newfit/reservation/domains/user/service/UserService.java
Labels: refactor

#214 fix: resolve conflict (#213)
  src/main/java/com/newfit/reservation/domains/reservation/service/ReservationService.java
Labels: bug

#216 refactor: Reservation의 repetitionNumber를 제거 (#215)
  src/main/java/com/newfit/reservation/domains/reservation/domain/Reservation.java
  src/main/java/com/newfit/reservation/domains/reservation/dto/request/ReservationRequest.java
  src/main/java/com/newfit/reservation/domains/reservation/dto/request/ReservationUpdateRequest.java
  src/main/java/com/newfit/reservation/domains/reservation/service/ReservationService.java
  src/main/java/com/newfit/reservation/domains/routine/service/RoutineService.java
Labels: refactor

#219 chore: dto 내부에 있는 id 필드를 구체적인 이름으로 변경 (#218)
  src/main/java/com/newfit/reservation/domains/authority/dto/response/ReservationResponse.java
  src/main/java/com/newfit/reservation/domains/reservation/dto/response/ReservationResponse.java
Labels: chore

#221 chore: ReservationApiController의 endpoint를 수정 (#220)
  src/main/java/com/newfit/reservation/domains/reservation/controller/ReservationApiController.java
Labels: chore

#222 bug: 예약 수정 로직 수정 (#217)
  src/main/java/com/newfit/reservation/domains/equipment/dto/response/EquipmentInfoResponse.java
  src/main/java/com/newfit/reservation/domains/equipment/repository/EquipmentGymRepository.java
  src/main/java/com/newfit/reservation/domains/reservation/controller/ReservationApiController.java
  src/main/java/com/newfit/reservation/domains/reservation/domain/Reservation.java
  src/main/java/com/newfit/reservation/domains/reservation/dto/request/ReservationUpdateRequest.java
  src/main/java/com/newfit/reservation/domains/reservation/dto/response/EquipmentGymsListResponse.java
  src/main/java/com/newfit/reservation/domains/reservation/dto/response/ReservationInfoResponse.java
  src/main/java/com/newfit/reservation/domains/reservation/repository/ReservationRepository.java
  src/main/java/com/newfit/reservation/domains/reservation/service/ReservationService.java
Labels: bug

#226 refactor: 루틴 수정의 로직 개선 (#223)
  src/main/java/com/newfit/reservation/domains/routine/domain/EquipmentRoutine.java
  src/main/java/com/newfit/reservation/domains/routine/service/EquipmentRoutineService.java
Labels: refactor

#227 chore: 메서드의 순서를 변경하여 가독성 개선 (#225)
  src/main/java/com/newfit/reservation/domains/routine/service/RoutineService.java
Labels: chore

#228 refactor: Userservice userdetail 메소드 내부 수정 (#224)
  src/main/java/com/newfit/reservation/domains/user/service/UserService.java
Labels: refactor

#230 feat: user-id만 가진 상태로 마이페이지 접근할 경우에 대한 로직 추가 (#229)
  src/main/java/com/newfit/reservation/domains/user/controller/UserApiController.java
  src/main/java/com/newfit/reservation/domains/user/dto/response/UserAuthorityInfoResponse.java
  src/main/java/com/newfit/reservation/domains/user/dto/response/UserDetailResponse.java
  src/main/java/com/newfit/reservation/domains/user/dto/response/UserInfoResponse.java
  src/main/java/com/newfit/reservation/domains/user/service/UserService.java
Labels: feature

#238 chore: 특정 루틴 세부사항 조회하는 api의 parameter 변수명 변경 (#233)
  src/main/java/com/newfit/reservation/domains/routine/controller/RoutineApiController.java
Labels: chore

#239 refactor: 예약 등록 및 수정 api endpoint에서 param을 pathvariable로 수정 (#234)
  src/main/java/com/newfit/reservation/domains/reservation/controller/ReservationApiController.java
Labels: refactor

#240 chore: AuthorityApiController listReservation 메소드의 endpoint 수정 (#235)
  src/main/java/com/newfit/reservation/domains/authority/controller/AuthorityApiController.java
Labels: chore

#241 refactor: UserAndPendingResponse의 username을 nickname으로 변경 (#236)
  src/main/java/com/newfit/reservation/domains/authority/dto/response/manager/UserAndPendingResponse.java
Labels: refactor

#242 feat: User drop 메소드 내부에 사용자 이메일을 통한 본인 확인 로직 추가 (#237)
  src/main/java/com/newfit/reservation/common/exception/ErrorCode.java
  src/main/java/com/newfit/reservation/domains/user/controller/UserApiController.java
  src/main/java/com/newfit/reservation/domains/user/domain/User.java
  src/main/java/com/newfit/reservation/domains/user/dto/request/UserDropRequest.java
  src/main/java/com/newfit/reservation/domains/user/service/UserService.java
Labels: feature

#244 chore: 일관성을 위한 메소드 이름 수정 (#243)
  src/main/java/com/newfit/reservation/domains/routine/service/EquipmentRoutineService.java
Labels: chore

#246 refactor: Authority의 accepted가 false인 경우 authority-id가 필요한 api 접근을 제한하도록 수정 (#245)
  src/main/java/com/newfit/reservation/common/auth/config/WebSecurityConfig.java
  src/main/java/com/newfit/reservation/common/auth/jwt/TokenAuthenticationFilter.java
  src/main/java/com/newfit/reservation/common/auth/jwt/TokenProvider.java
  src/main/java/com/newfit/reservation/common/exception/CustomExceptionHandlingFilter.java
  src/main/java/com/newfit/reservation/common/exception/ErrorCode.java
  src/main/java/com/newfit/reservation/domains/authority/service/AuthorityService.java
Labels: refactor

#232 chore: Enum name convention (#231)
  src/main/java/com/newfit/reservation/common/auth/AuthorityCheckService.java
  src/main/java/com/newfit/reservation/common/auth/jwt/TokenAuthenticationFilter.java
  src/main/java/com/newfit/reservation/common/auth/jwt/TokenProvider.java
  src/main/java/com/newfit/reservation/common/auth/oauth/OAuth2UserCustomService.java
  src/main/java/com/newfit/reservation/common/exception/CustomException.java
  src/main/java/com/newfit/reservation/common/exception/CustomExceptionHandlingFilter.java
  src/main/java/com/newfit/reservation/common/exception/ErrorCodeType.java
  src/main/java/com/newfit/reservation/common/exception/ExceptionResponse.java
  src/main/java/com/newfit/reservation/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/newfit/reservation/domains/auth/domain/OAuthHistory.java
  src/main/java/com/newfit/reservation/domains/auth/domain/ProviderType.java
  src/main/java/com/newfit/reservation/domains/auth/repository/OAuthHistoryRepository.java
  src/main/java/com/newfit/reservation/domains/authority/domain/Authority.java
  src/main/java/com/newfit/reservation/domains/authority/domain/RoleType.java
  src/main/java/com/newfit/reservation/domains/authority/dto/request/manager/RegisterEquipmentRequest.java
  src/main/java/com/newfit/reservation/domains/authority/dto/request/manager/UpdateConditionRequest.java
  src/main/java/com/newfit/reservation/domains/authority/dto/response/EquipmentResponse.java
  src/main/java/com/newfit/reservation/domains/authority/repository/AuthorityRepository.java
  src/main/java/com/newfit/reservation/domains/authority/service/AuthorityService.java
  src/main/java/com/newfit/reservation/domains/credit/service/CreditService.java
  src/main/java/com/newfit/reservation/domains/equipment/controller/EquipmentApiController.java
  src/main/java/com/newfit/reservation/domains/equipment/domain/ConditionType.java
  src/main/java/com/newfit/reservation/domains/equipment/domain/Equipment.java
  src/main/java/com/newfit/reservation/domains/equipment/domain/EquipmentGym.java
  src/main/java/com/newfit/reservation/domains/equipment/domain/PurposeType.java
  src/main/java/com/newfit/reservation/domains/equipment/dto/response/EquipmentResponse.java
  src/main/java/com/newfit/reservation/domains/equipment/repository/EquipmentRepository.java
  src/main/java/com/newfit/reservation/domains/equipment/service/EquipmentGymService.java
  src/main/java/com/newfit/reservation/domains/equipment/service/EquipmentService.java
  src/main/java/com/newfit/reservation/domains/gym/domain/Gym.java
  src/main/java/com/newfit/reservation/domains/reservation/domain/Reservation.java
  src/main/java/com/newfit/reservation/domains/reservation/domain/StatusType.java
  src/main/java/com/newfit/reservation/domains/reservation/service/ReservationService.java
  src/main/java/com/newfit/reservation/domains/routine/dto/response/RoutineDetailEquipmentResponse.java
  src/main/java/com/newfit/reservation/domains/routine/service/EquipmentRoutineService.java
  src/main/java/com/newfit/reservation/domains/routine/service/RoutineService.java
  src/main/java/com/newfit/reservation/domains/user/domain/User.java
  src/main/java/com/newfit/reservation/domains/user/service/UserService.java
Labels: chore

#247 refactor: 엔티티 delete 로직 내부에서 연관관계를 맺은 모든 엔티티들도 같이 삭제하도록 수정 (#178)
  src/main/java/com/newfit/reservation/domains/authority/controller/ManagerApiController.java
  src/main/java/com/newfit/reservation/domains/authority/domain/Authority.java
  src/main/java/com/newfit/reservation/domains/authority/service/AuthorityService.java
  src/main/java/com/newfit/reservation/domains/dev/domain/Proposal.java
  src/main/java/com/newfit/reservation/domains/dev/domain/Report.java
  src/main/java/com/newfit/reservation/domains/dev/repository/ProposalRepository.java
  src/main/java/com/newfit/reservation/domains/dev/repository/ReportRepository.java
  src/main/java/com/newfit/reservation/domains/equipment/domain/Equipment.java
  src/main/java/com/newfit/reservation/domains/equipment/domain/EquipmentGym.java
  src/main/java/com/newfit/reservation/domains/equipment/service/EquipmentGymService.java
  src/main/java/com/newfit/reservation/domains/equipment/service/EquipmentService.java
  src/main/java/com/newfit/reservation/domains/reservation/domain/Reservation.java
  src/main/java/com/newfit/reservation/domains/routine/domain/EquipmentRoutine.java
  src/main/java/com/newfit/reservation/domains/routine/repository/EquipmentRoutineRepository.java
  src/main/java/com/newfit/reservation/domains/user/domain/User.java
  src/main/java/com/newfit/reservation/domains/user/service/UserService.java
Labels: refactor
