Repository NewFit/NewFit-Backend, pull requests merged in 2023-11, with the labels that each got.

#251 refactor: Routine에 EquipmentRoutine과의 양방향 연관 관계 설정 및 cascade 적용 (#250)
  src/main/java/com/newfit/reservation/domains/authority/service/AuthorityService.java
  src/main/java/com/newfit/reservation/domains/routine/domain/Routine.java
  src/main/java/com/newfit/reservation/domains/routine/repository/EquipmentRoutineRepository.java
  src/main/java/com/newfit/reservation/domains/routine/service/RoutineService.java
  src/main/java/com/newfit/reservation/domains/user/service/UserService.java
Labels: refactor

#253 refactor: 인증 로직 변경 (#252)
  build.gradle
  src/main/java/com/newfit/reservation/common/auth/config/WebSecurityConfig.java
  src/main/java/com/newfit/reservation/common/auth/oauth/CustomOAuth2User.java
  src/main/java/com/newfit/reservation/common/auth/oauth/OAuth2AuthorizationRequestCookieRepository.java
  src/main/java/com/newfit/reservation/common/auth/oauth/OAuth2UserCustomService.java
  src/main/java/com/newfit/reservation/common/auth/oauth/handler/OAuth2FailureHandler.java
  src/main/java/com/newfit/reservation/common/auth/oauth/handler/OAuth2SuccessHandler.java
  src/main/java/com/newfit/reservation/common/auth/util/CookieUtil.java
  src/main/java/com/newfit/reservation/domains/auth/controller/TokenApiController.java
  src/main/java/com/newfit/reservation/domains/auth/domain/IdType.java
  src/main/java/com/newfit/reservation/domains/auth/dto/request/IssueTokenRequest.java
  src/main/java/com/newfit/reservation/domains/auth/dto/response/IssuedTokenResponse.java
  src/main/java/com/newfit/reservation/domains/auth/service/TokenService.java
Labels: refactor

#255 feat: 어드민 페이지 생성 (#254)
  build.gradle
  src/main/java/com/newfit/reservation/common/auth/config/WebSecurityConfig.java
  src/main/java/com/newfit/reservation/domains/admin/controller/AdminController.java
  src/main/java/com/newfit/reservation/domains/authority/controller/AdminManagerController.java
  src/main/java/com/newfit/reservation/domains/authority/domain/Authority.java
  src/main/java/com/newfit/reservation/domains/authority/domain/RoleType.java
  src/main/java/com/newfit/reservation/domains/authority/dto/request/admin/AssignManagerRequest.java
  src/main/java/com/newfit/reservation/domains/authority/repository/AuthorityRepository.java
  src/main/java/com/newfit/reservation/domains/authority/service/AdminManagerService.java
  src/main/java/com/newfit/reservation/domains/gym/controller/AdminGymController.java
  src/main/java/com/newfit/reservation/domains/gym/domain/BusinessTime.java
  src/main/java/com/newfit/reservation/domains/gym/domain/Gym.java
  src/main/java/com/newfit/reservation/domains/gym/dto/request/admin/CreateGymRequest.java
  src/main/java/com/newfit/reservation/domains/gym/dto/request/admin/UpdateGymRequest.java
  src/main/java/com/newfit/reservation/domains/gym/service/AdminGymService.java
  src/main/resources/templates/v1/admin/gyms/addGymForm.html
  src/main/resources/templates/v1/admin/gyms/editGymForm.html
  src/main/resources/templates/v1/admin/gyms/gym.html
  src/main/resources/templates/v1/admin/gyms/index.html
  src/main/resources/templates/v1/admin/index.html
  src/main/resources/templates/v1/admin/managers/addManagerForm.html
Labels: feature

#257 bug: OAuth2SuccessHandler에서 admin의 요청만을 처리하도록 수정 (#256)
  build.gradle
  src/main/java/com/newfit/reservation/common/auth/config/WebSecurityConfig.java
  src/main/java/com/newfit/reservation/common/auth/jwt/TokenAuthenticationFilter.java
  src/main/java/com/newfit/reservation/common/auth/jwt/TokenProvider.java
  src/main/java/com/newfit/reservation/common/auth/oauth/CustomOAuth2User.java
  src/main/java/com/newfit/reservation/common/auth/oauth/OAuth2AuthorizationRequestCookieRepository.java
  src/main/java/com/newfit/reservation/common/auth/oauth/OAuth2UserCustomService.java
  src/main/java/com/newfit/reservation/common/auth/oauth/handler/OAuth2FailureHandler.java
  src/main/java/com/newfit/reservation/common/auth/oauth/handler/OAuth2SuccessHandler.java
  src/main/java/com/newfit/reservation/common/auth/util/CookieUtil.java
  src/main/java/com/newfit/reservation/common/exception/ErrorCodeType.java
  src/main/java/com/newfit/reservation/domains/auth/controller/TokenApiController.java
  src/main/java/com/newfit/reservation/domains/auth/domain/IdType.java
  src/main/java/com/newfit/reservation/domains/auth/dto/request/IssueTokenRequest.java
  src/main/java/com/newfit/reservation/domains/auth/service/TokenService.java
Labels: bug, refactor

#259 feature: 커스텀 ENUM 검증 어노테이션 구현 (#258)
  src/main/java/com/newfit/reservation/common/exception/ErrorCodeType.java
  src/main/java/com/newfit/reservation/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/newfit/reservation/common/validator/EnumValue.java
  src/main/java/com/newfit/reservation/common/validator/EnumValueValidator.java
  src/main/java/com/newfit/reservation/domains/auth/domain/ProviderType.java
  src/main/java/com/newfit/reservation/domains/auth/dto/request/IssueTokenRequest.java
Labels: feature

#261 chore: 개발 서버 CI/CD (#260)
  .github/workflows/cicd.yml
Labels: chore

#266 fix: 쿼리에 사용할 검색 키워드 생성 함수 수정 (#265)
  src/main/java/com/newfit/reservation/domains/gym/service/GymService.java
Labels: bug

#264 refactor: 헬스장 전체 조회 시 response에 헬스장 id도 포함하도록 수정 (#263)
  src/main/java/com/newfit/reservation/domains/authority/dto/response/GymResponse.java
  src/main/java/com/newfit/reservation/domains/gym/dto/response/GymResponse.java
Labels: refactor

#271 chore: querydsl 관련 config (#270)
  build.gradle
  src/main/java/com/newfit/reservation/common/config/QuerydslConfig.java
Labels: chore
