Repository NewFit/NewFit-Backend, pull requests merged in 2023-12, with the labels that each got.

#273 refactor: AuthorityRepository의 @Query문을 querydsl로 변경 (#272)
  src/main/java/com/newfit/reservation/domains/authority/repository/AuthorityRepository.java
  src/main/java/com/newfit/reservation/domains/authority/repository/AuthorityRepositoryCustom.java
  src/main/java/com/newfit/reservation/domains/authority/repository/AuthorityRepositoryImpl.java
  src/test/java/com/newfit/reservation/domains/authority/repository/AuthorityRepositoryTest.java
Labels: refactor

#279 refactor: ReservationRepository에 querydsl 적용 (#274)
  src/main/java/com/newfit/reservation/domains/reservation/repository/ReservationRepository.java
  src/main/java/com/newfit/reservation/domains/reservation/repository/ReservationRepositoryCustom.java
  src/main/java/com/newfit/reservation/domains/reservation/repository/ReservationRepositoryImpl.java
  src/test/java/com/newfit/reservation/domains/reservation/repository/ReservationRepositoryTest.java
Labels: refactor

#281 bug: 동일 사용자가 같은 헬스장에 중복해서 등록 요청을 보내지 못하도록 수정 (#280)
  src/main/java/com/newfit/reservation/common/exception/ErrorCodeType.java
  src/main/java/com/newfit/reservation/domains/authority/repository/AuthorityRepository.java
  src/main/java/com/newfit/reservation/domains/authority/repository/AuthorityRepositoryCustom.java
  src/main/java/com/newfit/reservation/domains/authority/repository/AuthorityRepositoryImpl.java
  src/main/java/com/newfit/reservation/domains/authority/service/AuthorityService.java
  src/test/java/com/newfit/reservation/domains/authority/repository/AuthorityRepositoryTest.java
  src/test/java/com/newfit/reservation/domains/authority/service/AuthorityServiceTest.java
Labels: bug

#283 refactor: GymRepository에 querydsl 적용 (#275)
  src/main/java/com/newfit/reservation/domains/gym/repository/GymRepository.java
  src/main/java/com/newfit/reservation/domains/gym/repository/GymRepositoryCustom.java
  src/main/java/com/newfit/reservation/domains/gym/repository/GymRepositoryImpl.java
  src/main/java/com/newfit/reservation/domains/gym/service/GymService.java
  src/test/java/com/newfit/reservation/domains/gym/repository/GymRepositoryTest.java
Labels: refactor

#288 fix: 서브쿼리의 syntax error 수정 (#287)
  src/main/java/com/newfit/reservation/domains/credit/repository/CreditRepository.java
  src/test/java/com/newfit/reservation/domains/credit/repository/CreditRepositoryTest.java
Labels: bug

#292 feat: api 호출 시 로그 기록하는 aop 추가 (#291)
  src/main/java/com/newfit/reservation/common/logger/ApiLoggerAOP.java
Labels: feature

#293 fix: 루틴 수정 api 버그 해결 (#289)
  src/main/java/com/newfit/reservation/domains/routine/service/EquipmentRoutineService.java
  src/test/java/com/newfit/reservation/domains/routine/service/RoutineServiceTest.java
Labels: bug

#295 refactor: response에 duration 추가 (#294)
  src/main/java/com/newfit/reservation/domains/routine/dto/response/RoutineDetailEquipmentResponse.java
  src/main/java/com/newfit/reservation/domains/routine/service/RoutineService.java
  src/test/java/com/newfit/reservation/domains/routine/service/RoutineServiceTest.java
Labels: refactor

#301 refactor: login response의 사용자 정보를 리스트로 변경 (#299)
  src/main/java/com/newfit/reservation/domains/auth/dto/response/IdInformationResponse.java
  src/main/java/com/newfit/reservation/domains/auth/dto/response/IssuedTokenResponse.java
  src/main/java/com/newfit/reservation/domains/auth/service/TokenService.java
Labels: refactor

#300 chore: provider type에 apple 추가 (#298)
  src/main/java/com/newfit/reservation/domains/auth/domain/ProviderType.java
Labels: chore

#303 refactor: ReservationDetailResponse dto에 equipment_id를 추가 (#302)
  src/main/java/com/newfit/reservation/domains/authority/dto/response/ReservationDetailResponse.java
Labels: refactor

#306 refactor: 로그아웃 로직 수정 (#305)
  src/main/java/com/newfit/reservation/common/auth/config/WebSecurityConfig.java
  src/main/java/com/newfit/reservation/common/auth/jwt/TokenProvider.java
Labels: refactor

#308 refactor: AuthorityGymResponse 내부에 accepted 필드 추가 (#307)
  src/main/java/com/newfit/reservation/domains/user/dto/response/AuthorityGymResponse.java
Labels: refactor
